platform :ios, '14.5'

target 'App' do
  use_frameworks!

  pod 'SwiftLint'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.5'
    end
  end
end
